services:
  loggerbot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      "./.env"
    links:
      - postgres
      - redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  postgres:
    image: postgres
    environment:
        - POSTGRES_USER=${PGUSER}
        - POSTGRES_PASSWORD=${PGPASSWORD}
        - POSTGRES_DB=${PGDATABASE}
    env_file:
      "./.env"
    ports:
        - "5432:5432"
    volumes:
        - redisdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
  redisdata: